### ISSUE TITLE
Flow schetsen

### ISSUE THREAD

**Issue by jornveltrop** [CMD-JOBS/CMD-JOBS#10]
Ik heb wireframe schetsen gemaakt van de flow app, ik heb de volgende functies inbegrepen:
- [ ] (eventuele) start/login scherm (Account)
- [ ] Profiel aanmaken (Voorkeuren)
- [ ] Lijst met voorgestelde Jobs (filter + opslaan)
- [ ] Detail pagina jobs 
- [ ] Reageren op jobs (Contact)

Ik heb 2 verschillende opties getekend voor de flow jobs opslaan en reageren op jobs.

[wireframe schetsen](https://github.com/CMD-JOBS/CMD-JOBS/blob/main/docs/wireframes%20cmd%20jobs.pdf)

**Comment by YunusEmreCMD** [comment]
Ashley ziet er goed uit, lekker uitgebreid geschetst, netjes :) Alleen ik denk dat we nog een inlog knop missen op het begin scherm, misschien moeten we eerst de mogelijkheid geven om in te loggen en als de gebruiker geen account heeft, kan de gebruiker een account aanmaken door op een link te klikken bijvoorbeeld "Aanmelden".  Maar de schetsen geven een goed inzicht welke richting we op kunnen gaan met de applicatie.

**Comment by DylanTroff** [comment]
Ziet er echt top uit! Laten we snel even bij elkaar komen om dit samen door te nemen. De inlog knop die @YunusEmreCMD vermeld zou goed van pas komen.

**Comment by jornveltrop** [comment]
Ik sluit mij aan bij de andere. Erg nice gedaan! 

Misschien is de search button links onder in het menu niet eens nodig en zouden we die weg kunnen halen. Hoe denkt de rest daar over?

Laten we inderdaad zoals @DylanTroff zegt morgen even in een video-call bespreken voor welke optie we gaan. Dan maken we daarin meteen de taakverdeling voor deze opzet!

**Comment by robbinux** [comment]
Netjes Ashley, ik denk direct kunnen reageren bij het zien van de job (optie 1) wel beter is alleen dit is meer een nice-to-have dan een must.
