### ISSUE TITLE
2de versie van wireframe maken

### ISSUE THREAD

**Issue by ashleyKeuning** [CMD-JOBS/CMD-JOBS#18]
Na de eerste versie van de wireframe te hebben besproken met het team, heb ik een tweede versie van de wireframe gemaakt in XD, dit hebben we ook weer samen besproken.

[wireframe versie 2](https://github.com/CMD-JOBS/CMD-JOBS/blob/main/docs/wireframe%202%20cmd%20jobs.pdf)

**Comment by jornveltrop** [comment]
Top!

**Comment by YunusEmreCMD** [comment]
Na aanleiding van de feedback op de eerste versie van de wireframes, goede vooruitgang! Goed dat je verschillende versies hebt gemaakt!

**Comment by DylanTroff** [comment]
Awesome! Dit ziet er top uit.
