### ISSUE TITLE
Topic - Hash passwords

### ISSUE THREAD

**Issue by DylanTroff** [CMD-JOBS/CMD-JOBS#21]
Onderzoek doen en het toepassen van Hash op wachtwoorden.

**Comment by YunusEmreCMD** [comment]
Nice research Dylan! Leuk dat je ook code blocks hebt gebruikt. Alleen voor een volgende keer zou ik ook bij de code blocks neerzetten, in welke taal de code is geschreven dat is wat cleaner.

Als je bij een code block na de "```" aangeeft uit welke taal de code afkomstig is, wordt deze ook omgezet naar de kleuren die daarbij horen zie hieronder:

zonder ```js

```
bcrypt.genSalt(10, (err, salt) => {
      bcrypt.hash(newUser.password, salt,(err, hash)=>{
        newUser.password = hash;
   )};
)};
``` 

met ```js

```js
bcrypt.genSalt(10, (err, salt) => {
      bcrypt.hash(newUser.password, salt,(err, hash)=>{
        newUser.password = hash;
   )};
)};
``` 

Je kan ook html, CSS etc doen =>

```css

div {
  font-size: 12px;
  color: red;
  margin: 1em;
}

```

Is gewoon een klein dingetje, verder super netjes! 😄
