### ISSUE TITLE
Inlog functie aan de databbase koppelen

### ISSUE THREAD

**Issue by ashleyKeuning** [CMD-JOBS/CMD-JOBS#35]

**Comment by YunusEmreCMD** [comment]
Inlog functie werkt, is ook juist gekoppeld aan de DB. Netjes gedaan!

**Comment by ashleyKeuning** [comment]
de inlog functie werkt goed en daarbij ook nog eens goed gekoppeld aan de database, zodat het per user inlogt!!!
