### ISSUE TITLE
Loguit functie

### ISSUE THREAD

**Issue by jornveltrop** [CMD-JOBS/CMD-JOBS#42]

**Comment by YunusEmreCMD** [comment]
Snel gefixt! Werkt top! Deze issue kan geclosed worden.

**Comment by ashleyKeuning** [comment]
log uit functie snel gefixt, en werkt zoals verwacht!!

**Comment by ashleyKeuning** [comment]
log uit functie snel gefixt, en werkt zoals verwacht!!
