### ISSUE TITLE
Styling van website

### ISSUE THREAD

**Issue by jornveltrop** [CMD-JOBS/CMD-JOBS#44]
- [x] Inloggen @ashleyKeuning 
- [x] Registreren @ashleyKeuning 
- [x] Error styling @ashleyKeuning 
- [x] Profiel toevoegen @robbinux 
- [x] Profiel + loguit button @robbinux 
- [x] Resultaten @robbinux 
- [x] Opgeslagen @robbinux

**Comment by jornveltrop** [comment]
@YunusEmreCMD heb jij dit inmiddels helemaal omgezet in Sass?

**Comment by YunusEmreCMD** [comment]
@jornveltrop alles is omgezet naar Sass!
